# Generated by Django 5.0.6 on 2024-06-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_manager_app', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='high', max_length=10),
        ),
    ]
